export const notification = {
 ERROR: 'SET_NOTIFICATION_ERROR',
 INFO: 'SET_NOTIFICATION_INFO',
 REMOVE: 'REMOVE_NOTIFICATION',
 SHOW: 'SHOW_NOTIFICATION',
 SUCCESS: 'SET_NOTIFICATION_SUCCESS',
 WARNING: 'SET_NOTIFICATION_WARNING',
}