export const GET_INITIAL_LINKS = 'GET_INITIAL_LINKS'
export const GET_INITIAL_COLLECTIONS = 'GET_INITIAL_COLLECTIONS'
export const GET_ALL_TAGS = 'GET_ALL_TAGS'
export const UPDATE_TAGS = 'UPDATED_TAGS'